/**
 * Analytics API service for fetching and exporting user analytics data.
 */

const API_BASE = 'http://localhost:8000/api';

export interface AnalyticsSummary {
    total_calls: number;
    total_call_duration_minutes: number;
    average_call_duration_seconds: number;
    scam_calls_detected: number;
    scam_detection_rate_percent: number;
    alerts_sent_to_contacts: number;
}

export interface RiskBreakdown {
    high_risk_calls: number;
    medium_risk_calls: number;
    low_risk_calls: number;
}

export interface ActivityTimestamps {
    first_call: string | null;
    last_call: string | null;
    last_scam_detected: string | null;
}

export interface WeeklyActivity {
    [week: string]: {
        calls: number;
        scams: number;
        duration: number;
    };
}

export interface RecentCaller {
    phone: string;
    last_call: string;
    risk: number;
}

export interface ExportedAnalytics {
    summary: AnalyticsSummary;
    risk_breakdown: RiskBreakdown;
    activity: ActivityTimestamps;
    weekly_activity: WeeklyActivity;
    recent_callers: RecentCaller[];
    exported_at: string;
}

export interface UserAnalyticsRaw {
    id: string;
    total_calls: number;
    total_call_duration_seconds: number;
    total_scam_calls: number;
    total_suspicious_calls: number;
    total_safe_calls: number;
    total_alerts_sent: number;
    total_scams_blocked: number;
    total_questions_generated: number;
    weekly_stats: WeeklyActivity;
    daily_stats: { [date: string]: { calls: number; scams: number } };
    high_risk_calls: number;
    medium_risk_calls: number;
    low_risk_calls: number;
    unique_callers_count: number;
    recent_callers: RecentCaller[];
    first_call_at: string | null;
    last_call_at: string | null;
    last_scam_detected_at: string | null;
    created_at: string;
    updated_at: string;
}

/**
 * Fetch raw analytics data for a user.
 */
export async function fetchUserAnalytics(userId: string): Promise<UserAnalyticsRaw | null> {
    try {
        const response = await fetch(`${API_BASE}/analytics?user_id=${encodeURIComponent(userId)}`);
        const data = await response.json();

        if (data.error) {
            console.log('No analytics data found for user');
            return null;
        }

        return data as UserAnalyticsRaw;
    } catch (error) {
        console.error('Error fetching analytics:', error);
        return null;
    }
}

/**
 * Export analytics data in shareable format.
 */
export async function exportAnalytics(userId: string): Promise<ExportedAnalytics | null> {
    try {
        const response = await fetch(`${API_BASE}/analytics/export?user_id=${encodeURIComponent(userId)}`);
        const data = await response.json();

        if (data.error) {
            console.log('No analytics data to export');
            return null;
        }

        return data as ExportedAnalytics;
    } catch (error) {
        console.error('Error exporting analytics:', error);
        return null;
    }
}

/**
 * Generate a text report from exported analytics for sharing.
 */
export function generateShareableReport(data: ExportedAnalytics, userName?: string): string {
    const name = userName || 'Your loved one';
    const lines = [
        `📊 KOVA Call Protection Report`,
        `Generated: ${new Date(data.exported_at).toLocaleDateString()}`,
        ``,
        `👤 ${name}'s Call Summary`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `📞 Total Calls Monitored: ${data.summary.total_calls}`,
        `⏱️ Total Call Time: ${data.summary.total_call_duration_minutes} minutes`,
        `📈 Average Call Duration: ${data.summary.average_call_duration_seconds} seconds`,
        ``,
        `🛡️ Scam Protection`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `🚨 Scam Calls Detected: ${data.summary.scam_calls_detected}`,
        `📱 Alerts Sent to You: ${data.summary.alerts_sent_to_contacts}`,
        ``,
        `📊 Call Risk Breakdown`,
        `━━━━━━━━━━━━━━━━━━━━━━━━━━━`,
        `🔴 High Risk: ${data.risk_breakdown.high_risk_calls}`,
        `🟡 Medium Risk: ${data.risk_breakdown.medium_risk_calls}`,
        `🟢 Low Risk: ${data.risk_breakdown.low_risk_calls}`,
        ``,
        `This report was generated by KOVA - AI-Powered Scam Call Protection`,
    ];

    return lines.join('\n');
}

/**
 * Download analytics as a text file.
 */
export function downloadReportAsFile(report: string, fileName?: string): void {
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName || `kova-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
